title: "Courage, Healing, Love"
email: "mx [at] mxmarin.ca"
description: "Blogging about blood and stars."
baseurl: "" 
url: "https://blog.mxmarin.ca" 
permalink: pretty
author: "M-X"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
